# Generated by Django 5.0.6 on 2026-06-01 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_options_task_completed_at_task_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('project_created', models.BooleanField(default=True)),
                ('project_deleted', models.BooleanField(default=True)),
                ('task_created', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=True)),
                ('task_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
